/********************************************************************
 * Automatically generated by ARUnit
 * Filename: Rte_SWC_DoorAlgo_.c
 * Generated on: Tue Aug 13 7:34:13 EET
 ********************************************************************/

#include "string.h"
#include "Rte_SWC_DoorAlgo.h"


Rte_DE_u8_t DoorSensorState_PP_DoorState_DoorState;
Rte_DE_u8_t DoorLock_Indication_RP_DoorState_DoorState;


const Rte_CDS_SWC_DoorAlgo Rte_Instance_SWC_DoorAlgo = {
&DoorSensorState_PP_DoorState_DoorState
};

const Rte_CDS_SWC_DoorAlgo * const Rte_Inst_SWC_DoorAlgo = &Rte_Instance_SWC_DoorAlgo;


Std_ReturnType SWC_DoorAlgo_RP_CS_LedState_SetLedState_Buffer_retcode = RTE_E_OK;

FunctionPtr_SWC_DoorAlgo_RP_CS_LedState_SetLedState Rte_Call_SWC_DoorAlgo_RP_CS_LedState_SetLedState_Delegate = 0;

u8_t Rte_IRead_SWC_DoorAlgo_DoorLock_Indication_RP_DoorState_DoorState (void)
{
	return (Rte_Inst_SWC_DoorAlgo)->DoorLock_Indication_RP_DoorState_DoorState->value;
}
Std_ReturnType Rte_Call_SWC_DoorAlgo_RP_CS_LedState_SetLedState (u8_t LedState_IN)
{
	Std_ReturnType __result = SWC_DoorAlgo_RP_CS_LedState_SetLedState_Buffer_retcode;
	if ( Rte_Call_SWC_DoorAlgo_RP_CS_LedState_SetLedState_Delegate != 0 ) {
		__result = Rte_Call_SWC_DoorAlgo_RP_CS_LedState_SetLedState_Delegate(LedState_IN);
	}
	// Synch . To call operation runnable
	Led_Switch_Runnable(LedState_IN);
	return __result;
}
