/********************************************************************
 * Automatically generated by ARUnit
 * Filename: Rte_SWC_DoorAlgo.h
 * Generated on: Tue Aug 13 7:34:13 EET
 ********************************************************************/

#ifndef RTE_SWC_DOORALGO_H
#define RTE_SWC_DOORALGO_H

#include "Rte_SWC_DoorAlgo_Type.h"

#ifdef __cplusplus
	extern "C" {
#endif /* __cplusplus */

/**************** component data structure definition ****************/

#ifndef IN_RTE_C
typedef const Rte_CDS_SWC_DoorAlgo * const Rte_Instance;
#endif

/************************* instance handle ***************************/

extern const Rte_CDS_SWC_DoorAlgo * const Rte_Inst_SWC_DoorAlgo;

/************************ application errors *************************/

#define RTE_E_CSIF_LedState_Error_Not_OK ((Std_ReturnType)1)
#define RTE_E_CSIF_LedState_Error_OK ((Std_ReturnType)0)

/*************************** init values *****************************/


/****************** per instance memory definition *******************/


/************************* exclusive areas ***************************/


/************************* RTE API mapping ***************************/

/*****************************************************
 * Port: 		RP_DoorState
 * Interface:	SRI_DoorState
 * DataElement:	DoorState
 * Runnable:	DoorLock_Indication
 *****************************************************/
extern u8_t Rte_IRead_SWC_DoorAlgo_DoorLock_Indication_RP_DoorState_DoorState (void);
#ifndef IN_RTE_C
#define Rte_IRead_DoorLock_Indication_RP_DoorState_DoorState() \
	Rte_IRead_SWC_DoorAlgo_DoorLock_Indication_RP_DoorState_DoorState()
#endif

/*****************************************************
 * Port: 		RP_CS_LedState
 * Interface:	CSIF_LedState
 * Operation:	SetLedState
 * Sync/Async:	Synchronous
 *****************************************************/
extern Std_ReturnType Rte_Call_SWC_DoorAlgo_RP_CS_LedState_SetLedState (u8_t LedState_IN);
#ifndef IN_RTE_C
#define Rte_Call_RP_CS_LedState_SetLedState(LedState_IN) \
	Rte_Call_SWC_DoorAlgo_RP_CS_LedState_SetLedState(LedState_IN)
#endif


/**************** event triggered runnable entities *******************/

/*****************************************************
 * Runnable: 	DoorLock_Indication
 * Period:		0.012
 *****************************************************/
extern void DoorLock_Indication_Runnable(void);


/******** ARUnit-specific function pointers for server call delegates *********/
typedef Std_ReturnType (*FunctionPtr_SWC_DoorAlgo_RP_CS_LedState_SetLedState)(u8_t LedState_IN);


#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */

#endif /* RTE_SWC_DOORALGO_H */
