/********************************************************************
 * Automatically generated by ARUnit
 * Filename: Rte_SWC_DoorAlgo_Type.h
 * Generated on: Tue Aug 13 7:34:13 EET
 ********************************************************************/

#ifndef RTE_SWC_DOORALGO_TYPE_H
#define RTE_SWC_DOORALGO_TYPE_H


#include "Rte_Type.h"

#ifdef __cplusplus
	extern "C" {
#endif /* __cplusplus */

/*************************** range types *****************************/

#define u8_t_LowerLimit  (0U)
#define u8_t_UpperLimit (255U)

/************************ enumeration types **************************/



#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */

#endif /* RTE_SWC_DOORALGO_TYPE_H */
