/********************************************************************
 * Automatically generated by ARUnit
 * Filename: Rte_Type.h
 * Generated on: Tue Aug 13 7:34:13 EET
 ********************************************************************/

#ifndef RTE_TYPE_H
#define RTE_TYPE_H


#include "Rte.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */
/**************************** datatypes ******************************/

typedef unsigned char u8_t;


/********************* mode declaration groups ***********************/


/********************** per instance memories ************************/


/******************* implicit buffer declaration *********************/

typedef struct {
	u8_t value;
} Rte_DE_u8_t;


/******************** component data structures **********************/

/*********************************************************************
 * component data structure for SWC: SWC_DoorAlgo 
 *********************************************************************/
typedef struct Rte_CDS_SWC_DoorAlgo
{
	/* Data Handles section*/
	Rte_DE_u8_t *DoorLock_Indication_RP_DoorState_DoorState;
	/* Per-Instance Memory Handles section*/
	/* Inter-runnable Variable Handles section*/
	/* Calibration Parameter Handles section*/
	/* Exclusive-area Handles section*/
	/* Port API Handles section*/
	/* Inter Runnable Variable API Handles section*/
} Rte_CDS_SWC_DoorAlgo;

/*********************************************************************
 * component data structure for SWC: SWC_DoorSensorAbstraction 
 *********************************************************************/
typedef struct Rte_CDS_SWC_DoorSensorAbstraction
{
	/* Data Handles section*/
	Rte_DE_u8_t *DoorSensorState_PP_DoorState_DoorState;
	/* Per-Instance Memory Handles section*/
	/* Inter-runnable Variable Handles section*/
	/* Calibration Parameter Handles section*/
	/* Exclusive-area Handles section*/
	/* Port API Handles section*/
	/* Inter Runnable Variable API Handles section*/
} Rte_CDS_SWC_DoorSensorAbstraction;

/*********************************************************************
 * component data structure for SWC: Compsit_DoorLock_SWC 
 *********************************************************************/
typedef struct Rte_CDS_Compsit_DoorLock_SWC
{
	/* Data Handles section*/
	/* Per-Instance Memory Handles section*/
	/* Inter-runnable Variable Handles section*/
	/* Calibration Parameter Handles section*/
	/* Exclusive-area Handles section*/
	/* Port API Handles section*/
	/* Inter Runnable Variable API Handles section*/
	uint8 _dummy;
} Rte_CDS_Compsit_DoorLock_SWC;


#ifdef __cplusplus
} /* extern "C" */
#endif /* __cplusplus */

#endif /* RTE_TYPE_H */
